name: hw_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  #getx state management 
  get: 4.6.5
  get_storage: ^2.0.3

  #dio service helper 
  dio: ^4.0.0

  #responsive ui screen 
  flutter_screenutil: ^5.5.1

  #check connectivity
  connectivity_plus: ^4.0.1

  #better toasts
  fluttertoast: ^8.0.6

  #zoomin zoomout image 
  pinch_zoom: ^1.0.0

  #cached image to better load image
  cached_network_image: ^3.2.0

  #alert widget 
  rflutter_alert: ^2.0.2

  # localization, date formater, etc.
  intl: ^0.18.1

  #shimmer loading 
  shimmer: ^3.0.0

  #more loading indicator 
  loading_indicator: 3.0.2

  #onion model class helper  
  fpdart: ^0.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #widget carousel slider 
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9

dependency_overrides:
    dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  pretty_dio_logger: ^1.3.1
  flutter_gen_runner:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/menu/
